---

# lldb 14 fails to load Python modules due to a wrong path. The workaround for
# this issue is to symlink the modules to the path that lldb expects.
# https://github.com/llvm/llvm-project/issues/55575

- name: Find all lldb Python files
  ansible.builtin.find:
    paths: /usr/lib/llvm-14/lib/python3.10/dist-packages/lldb
    file_type: file
  register: lldb_python_files

- name: Find all lldb Python modules
  ansible.builtin.find:
    paths: /usr/lib/llvm-14/lib/python3.10/dist-packages/lldb
    file_type: directory
  register: lldb_python_directories

- name: Fix llvm/llvm-project#55575
  ansible.builtin.file:
    src: "{{ item.path }}"
    dest: "/usr/lib/python3/dist-packages/lldb/{{ item.path | basename }}"
    state: link
  with_items: "{{ lldb_python_files.files + lldb_python_directories.files }}"
