---

- name: install Rust deps
  apt:
    name:
      - pkg-config
      - libssl-dev
    state: present

- name: install rustup in userspace for root
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y

- name: Configure update script service
  copy:
    src: team_login/
    dest: "{{ vars_team_login_path }}"

- name: Build team login cron job
  shell: "cd {{ vars_team_login_path }} && cargo build"

- name: Install the team login binary
  shell: "cp {{ vars_team_login_path }}/target/debug/team_login /etc/cron.team_login"

- name: Set up the team login cron job
  template:
    src: crontab_append
    dest: /etc/cron.d/team_login

- name: Set up the files that initially appear in a user's home dir
  copy:
    src: skel/
    dest: /etc/skel/

- name: install common tooling
  apt:
    name:
      - build-essential
      - cmake
      - python3
      - python-is-python3
      - clang
      - llvm
      - valgrind
      - ninja-build
    state: present
