---

- include_tasks: dependencies.yml
- include_tasks: quota.yml
- include_tasks: user_configuration.yml
- include_tasks: team_login.yml
- include_tasks: github.yml
- include_tasks: motd.yml
- include_tasks: scripts.yml
- include_tasks: fix_llvm_55575.yml
