name: Upload a Docker image to ECR
description: This action uploads a Docker image to AWS's container registry.

inputs:
  image:
    description: The name of the local image to upload
    required: true
  repository:
    description: The name of the ECR repository to upload to.
    required: true
  tag:
    description: The name of the docker image tag to use on ECR
    required: false
  region:
    description: The name of the AWS region the repository was created into.
    required: true
  redeploy_ecs_service:
    description: The name of the ECS service to redeploy after uploading the image.
    required: false
  redeploy_ecs_cluster:
    description: The name of the ECS cluster containing the service to redeploy.
    required: false
  aws_access_key_id:
    description: Value of AWS_ACCESS_KEY_ID
    required: true
  aws_secret_access_key:
    description: Value of AWS_SECRET_ACCESS_KEY
    required: true

runs:
  using: node16
  main: dist/index.js
