---

- name: create the gha-self-hosted group
  group:
    name: gha-self-hosted
    system: true
    state: present

- name: create the gha-self-hosted user
  user:
    name: gha-self-hosted
    group: gha-self-hosted
    groups:
      - kvm
    system: true
    create_home: false
    state: present

- name: upload sudoers configuration for gha-self-hosted
  template:
    src: sudoers
    dest: /etc/sudoers.d/gha-self-hosted

- name: create the required directories
  file:
    path: "{{ item }}"
    owner: gha-self-hosted
    group: gha-self-hosted
    mode: 0755
    state: directory

  loop:
    - /opt/gha-self-hosted
    - /opt/gha-self-hosted/rootfs
    - /opt/gha-self-hosted/bin

- name: clone the source repository
  git:
    repo: "{{ source_repo }}"
    dest: /opt/gha-self-hosted/source

  become_user: gha-self-hosted

- name: upload systemd services
  template:
    src: "systemd/{{ item }}"
    dest: "/etc/systemd/system/{{ item }}"

  loop:
    - gha-self-hosted-update.service
    - gha-self-hosted-update.timer
    - gha-self-hosted-rebuild-image.service
    - gha-self-hosted-rebuild-image.timer
    - gha-self-hosted-boot-time.service
  notify:
    - reload-systemd

- name: upload binaries
  template:
    src: "{{ item }}.sh"
    dest: "/opt/gha-self-hosted/bin/{{ item }}"
    owner: gha-self-hosted
    group: gha-self-hosted
    mode: 0755

  loop:
    - update-source
    - build-image

- name: enable systemd timers and services
  service:
    name: "{{ item }}"
    enabled: true
    state: started

  loop:
    - gha-self-hosted-update.timer
    - gha-self-hosted-rebuild-image.timer
    - gha-self-hosted-boot-time.service
