---

- name: restart-prometheus-ecs-discovery
  service:
    name: prometheus-ecs-discovery
    state: restarted

- name: restart-prometheus
  service:
    name: prometheus
    state: restarted

- name: restart-alertmanager
  service:
    name: alertmanager
    state: restarted

- name: restart-grafana
  service:
    name: grafana-server
    state: restarted

- name: reload-systemd
  shell: systemctl daemon-reload
