---

global_collect_metrics_from:
  - 52.9.166.219  # monitoring.infra.rust-lang.org

# Version of https://github.com/prometheus/node_exporter to install on our
# instances. The checksum is the hash of the downloadable tarball for the
# specified architecture, found in the GitHub releases.
node_exporter_version: 1.0.1
node_exporter_archs:
  x86_64:
    name: amd64
    checksum: sha256:3369b76cd2b0ba678b6d618deab320e565c3d93ccb5c2a0d5db51a53857768ae
  aarch64:
    name: arm64
    checksum: sha256:017514906922fcc4b7d727655690787faed0562bc7a17aa9f72b0651cb1b47fb

# Version of https://github.com/prometheus/prometheus to install on our
# instances. The checksum is the hash of the downloadable tarball for the
# specified architecture, found in the GitHub releases.
prometheus_version: 2.12.0
prometheus_arch: amd64
prometheus_checksum: sha256:b9f57b6e64fb3048742cfa7dbcc727e1df906d8020ef246a5e81b7959ae97e08

# Version of https://github.com/prometheus/alertmanager to install on our
# instances. The checksum is the hash of the downloadable tarball for the
# specified architecture, found in the GitHub releases.
alertmanager_version: 0.18.0
alertmanager_arch: amd64
alertmanager_checksum: sha256:5f17155d669a8d2243b0d179fa46e609e0566876afd0afb09311a8bc7987ab15

# Version of https://grafana.com to install in our instances. The checksum is
# the hash of the .deb for the specified architecture, found here:
# https://grafana.com/grafana/download
grafana_version: 7.5.5
grafana_arch: amd64
grafana_checksum: sha256:a6342dc645da72a92ac50ff053f9a9ca591f8334797174b9c70521bdcd349fe9

# Version of https://github.com/letsencrypt/pebble to install on our instances.
# The checksum is the hash of the downloadable binary for the specific
# architecture, found in the GitHub releases.
pebble_version: 2.2.2
pebble_arch: amd64
pebble_checksum: sha256:dcfe3106149885ebc3c1783aa1874b3cfb9bc78815737015127db641ef6be8c9

# Version of https://github.com/go-acme/lego to install on our instances. The
# checksum is the hash of the downloadable tarball for the specified
# architecture, found in the GitHub releases.
lego_version: 3.0.2
lego_arch: amd64
lego_checksum: sha256:6fb29df71eb920196459a4a8b5803c3e31639c26fb45967650a247a36f81f618

# Version of https://github.com/restic/restic to install on our instances. The
# checksum is the hash of the downloadable binary for the specified
# architecture, found in the GitHub release.
restic_version: 0.9.5
restic_arch: amd64
restic_checksum: sha256:08cd75e56a67161e9b16885816f04b2bf1fb5b03bc0677b0ccf3812781c1a2ec

# Version of https://www.packer.io to install on our instances. The checksum is
# available in a dedicated SHA256SUMS file.
packer_version: 1.5.6
packer_archs:
  x86_64:
    name: amd64
    checksum: sha256:2abb95dc3a5fcfb9bf10ced8e0dd51d2a9e6582a1de1cab8ccec650101c1f9df
  aarch64:
    name: arm64
    checksum: sha256:8942f3ae887a761befd9fa29da6f689050ce46b886910a6a439d6b49b5e463ae
