---

global_collect_metrics_from:
  - 52.9.166.219  # monitoring.infra.rust-lang.org

# Version of https://github.com/prometheus/node_exporter to install on our
# instances. The checksum is the hash of the downloadable tarball for the
# specified architecture, found in the GitHub releases.
node_exporter_version: 1.3.1
node_exporter_archs:
  x86_64:
    name: amd64
    checksum: sha256:68f3802c2dd3980667e4ba65ea2e1fb03f4a4ba026cca375f15a0390ff850949
  aarch64:
    name: arm64
    checksum: sha256:f19f35175f87d41545fa7d4657e834e3a37c1fe69f3bf56bc031a256117764e7

# Version of https://github.com/prometheus/prometheus to install on our
# instances. The checksum is the hash of the downloadable tarball for the
# specified architecture, found in the GitHub releases.
prometheus_version: 2.37.0
prometheus_arch: amd64
prometheus_checksum: sha256:ca70f5a261fd545da0b9893c42a73547a94ebd5111ef2b6b9f8742c5dbb73522

# Version of https://github.com/prometheus/alertmanager to install on our
# instances. The checksum is the hash of the downloadable tarball for the
# specified architecture, found in the GitHub releases.
alertmanager_version: 0.21.0
alertmanager_arch: amd64
alertmanager_checksum: sha256:9ccd863937436fd6bfe650e22521a7f2e6a727540988eef515dde208f9aef232

# Version of https://grafana.com to install in our instances. The checksum is
# the hash of the .deb for the specified architecture, found here:
# https://grafana.com/grafana/download
grafana_version: 9.0.6
grafana_arch: amd64
grafana_checksum: sha256:c80cc204fa96aa55c03d5f7ece341eca50af0b50b50151a2f189c30f588a68b1

# Version of https://github.com/letsencrypt/pebble to install on our instances.
# The checksum is the hash of the downloadable binary for the specific
# architecture, found in the GitHub releases.
pebble_version: 2.2.2
pebble_arch: amd64
pebble_checksum: sha256:dcfe3106149885ebc3c1783aa1874b3cfb9bc78815737015127db641ef6be8c9

# Version of https://github.com/go-acme/lego to install on our instances. The
# checksum is the hash of the downloadable tarball for the specified
# architecture, found in the GitHub releases.
lego_version: 3.0.2
lego_arch: amd64
lego_checksum: sha256:6fb29df71eb920196459a4a8b5803c3e31639c26fb45967650a247a36f81f618

# Version of https://github.com/restic/restic to install on our instances. The
# checksum is the hash of the downloadable binary for the specified
# architecture, found in the GitHub release.
restic_version: 0.9.5
restic_arch: amd64
restic_checksum: sha256:08cd75e56a67161e9b16885816f04b2bf1fb5b03bc0677b0ccf3812781c1a2ec

# Version of https://www.packer.io to install on our instances. The checksum is
# available in a dedicated SHA256SUMS file.
packer_version: 1.5.6
packer_archs:
  x86_64:
    name: amd64
    checksum: sha256:2abb95dc3a5fcfb9bf10ced8e0dd51d2a9e6582a1de1cab8ccec650101c1f9df
  aarch64:
    name: arm64
    checksum: sha256:8942f3ae887a761befd9fa29da6f689050ce46b886910a6a439d6b49b5e463ae

# Version of https://github.com/teralytics/prometheus-ecs-discovery to install
# in our instances. The checksum can be calculated by downloading the binary
# and checksumming it.
prometheus_ecs_discovery_version: 1.4.1
prometheus_ecs_discovery_checksum: 510cce227572739b6b545abdd31e259333081bd8606022948390278406008700
