[package]
name = "compute-static"
description = "Compute@Edge function for static.crates.io"
version = "0.1.0"
edition = "2021"

publish = false

[profile.release]
debug = 1

[dependencies]
fastly = "0.8.9"
log = "0.4.17"
