changelog-seen = 2

# Change this to the profile of your choice
profile = "compiler"

[rust]
# Build with debug assertions so we get useful RUSTC_LOG
# and notice debug assertions failing.
debug = true
