---

# Fetch all the group params from AWS SSM
ssm_crater_gcp_4: "{{ lookup('aws_ssm', '/prod/ansible/crater-gcp-4/', region='us-west-1', shortnames=true, bypath=true, recursive=true) }}"

vars_crater_token: "{{ ssm_crater_gcp_4['crater-token'] }}"
vars_crater_threads: 45
