---

- hosts: bastion
  become: yes
  become_user: root

  roles:

    - role: common
      papertrail_url: "{{ vars_papertrail_url }}"
      collect_metrics_from: "{{ global_collect_metrics_from }}"
      sudo_users:
        - aidanhs
        - simulacrum
        - pietro
      unprivileged_users:
        - onur  # docsrs.infra.rust-lang.org
        - joshua  # docsrs.infra.rust-lang.org
        - shep  # play.rust-lang.org
        - technetos  # RDS access to the discord-mods-bot database

    - role: bastion
