---

# Fetch all the group params from AWS SSM
ssm_crater: "{{ lookup('aws_ssm', '/prod/ansible/crater/', region='us-west-1', shortnames=true, bypath=true, recursive=true) }}"

vars_aws_credentials:
  role_arn: arn:aws:iam::890664054962:role/crater-agent
  access_key_id: "{{ ssm_crater['aws-access-key-id'] }}"
  secret_access_key: "{{ ssm_crater['aws-secret-access-key'] }}"

vars_crater_url: https://crater.rust-lang.org
