---

# Fetch all the group params from AWS SSM
ssm_monitoring: "{{ lookup('aws_ssm', '/prod/ansible/monitoring/', region='us-west-1', shortnames=true, bypath=true, recursive=true) }}"

vars_backup_password: "{{ ssm_monitoring['backup-password'] }}"
vars_backup_env:
  AWS_ACCESS_KEY_ID: "{{ ssm_monitoring['aws-access-key-id'] }}"
  AWS_SECRET_ACCESS_KEY: "{{ ssm_monitoring['aws-secret-access-key'] }}"
vars_postgresql_grafana_password: "{{ ssm_monitoring['postgresql-grafana-password'] }}"
vars_grafana_github_oauth_id: "{{ ssm_monitoring['grafana-github-oauth-id'] }}"
vars_grafana_github_oauth_secret: "{{ ssm_monitoring['grafana-github-oauth-secret'] }}"
vars_alertmanager_receiver_zulip_infra: "{{ ssm_monitoring['alertmanager-receiver-zulip-infra'] }}"
vars_alertmanager_receiver_discord_docsrs: "{{ ssm_monitoring['alertmanager-receiver-discord-docsrs'] }}"
vars_grafana_admin_password: "{{ ssm_monitoring['grafana-admin-password'] }}"

vars_prometheus_monitorbot_secret: "{{ lookup('aws_ssm', '/prod/monitorbot/secret', region='us-west-1') }}"

vars_backup_repository: s3:s3.amazonaws.com/rust-backups/monitoring
vars_grafana_domain: grafana.rust-lang.org
